plugins {
    id 'com.android.application'
}

android {
    namespace 'com.willsimon.retroxrealwalk'
    compileSdk 35

    defaultConfig {
        applicationId 'com.willsimon.retroxrealwalk'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }
}
